---
title: "Site History Update Log: LGBT History Scotland"
---

.Caption: Site History Update Log
[options="header, footer"]
[cols="0,3,0,0",width=90%]
|===
|Date |Recent Changes |Check |To Do
|20220107 |Problem wi SMG/Aberdeen/index.html.slim. Converted to index.html.erb.adoc by way of index_build.html|Check |To Do
|20230103 |created auto index to SMG - turn this into a real index. Current one is a  link to home for some reason |Check |To Do
|20221201|GHScans done including 1972||
|20221203|Links & MF in Mitchell Lib checked for missing up to & including 1982. 1982 has one argile not found on MF in edition indicated. Not sure about the other years. onwards||
|20221121|GH 1974 to 1982 uploaded. 1940 to 1973 #targets required. GH/index format needed. default_AsciiDoctor_Default_Stylesheet_20220319IansChangesAfterMinify.css   to server||
|20221117|source/IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/GD467_1_1_1IanDunnEarlyPapersAboutFoundingSMG +
/NEWindex.html.adoc created from oiginal index.html & ItemsToAddTo_index.html +
These were in a file in NoRecoll with entryies from GD467_1_1_1 from about 1968.||
|20221113|Now do GH 1982 from May onwards on to .adoc (wh) ||
|20221113|Glasgow Herald 1940-1981 to .adoc format. All google.news links for these. ||
|20220910|Glasgow Herald 1940-1973 google.news links added to site & uploadeds. ||
|20220627|discovery that file.html.erb.adoc should be file.erb.adoc cos erb renders to html5 by default||
|20220501|GD467_2 & GD467_3_1 index.html.erb added||
|20220412|GD467_4_36 Quentin Crisp letter images extra . in ..png changed to .png in filenames. +
 GD467_5 & 6 index.html added & links checked||

|20220407|Home page index.html.erb.adoc created from .html.erb||

|20220401|<%= stylesheet_link_tag '/stylesheets/default_AsciiDoctor_Default_Stylesheet_20220319IansChangesAfterMinify.css'  %> put in layout.erb +
    Sort out the css styles in this file| |

|20220401 |Updated SiteHistory.html.erb.adoc to be asciidoctor  | |

|20220303 |Glasgow Herald 1980 & 1969 missing editions found in Mitchell
Library | |

|20220205
|International Gay Rights Congress Edinburgh
/IDArc/GD467_5/GD467_5.html updated wii .html.slim. Cannot get
GD467_5/index.html.slim to redirect to GD467_5.html Need to use
middleman helper for url, I think
|spell
|do

|20220130 |GlasgowHerald1940to70, 1971, 1972, 1973, 1980 with newspaper
images transferred to server | |

|20220114 |Update Ruby to 3.1.0 - works `Using middleman-cli 5.0.0.rc.2
from https://github.com/middleman/middleman.git (at master@97ddbc5)'
Should I use v4.xxx? I think git used to serve that wi this command. | |

|20211201 |- TODO: Create footer or partial for the images at footer of
source/index.html and source/SiteHistoryLog.html.slim. Make image
similar in size | |

|20211003 |Internal links: all OK in entire site bundler exec middleman
build –clean ; htmlproofer build –extension .html –disable-external
–empty-alt-ignore –allow-hash-href false –allow-missing-href –alt-ignore
/.*/ | |

|20211003 |Use htmlproofer (.rb file) to check all ext links in entire
site OK bundler exec middleman build –clean ; htmlproofer build
–extension .html –external_only –empty-alt-ignore –allow-hash-href false
–allow-missing-href –alt-ignore /._/ –typhoeus-config ’ \{
``connecttimeout'': 60, ``timeout'': 100 } ’htmlproofer . –extension
.html –external_only –empty-alt-ignore –allow-hash-href false
–allow-missing-href –alt-ignore /._/ –typhoeus-config ’ \{
``connecttimeout'': 60, ``timeout'': 100 } ’ –hydra_config ’ \{
``max_concurrency'': 10 } ’ –timeframe ``1h'' –url-ignore
/._web.archive.org._/ –log-level :info | |

|19/9/2010 |- All external links checked All OK except for filofax.html
in web.archive.organise.organise. Adding 0 links to the cache… Removing
0 links from the cache… Checking 2 external links… Ran on 213 files! -
build/TimeLine/TimeLine.html * External link
'https://web.archive.org/web/20071028222010/http://www.knittingcircle.org.uk/filofax.html#Stonewall'
 (filofax.html inaccessible on Wayback Machine 2021)  * External link
'https://web.archive.org/web/20071028222010/http://www.knittingcircle.org.uk/filofax.html#Switchboard'
failed: 503 No error HTML-Proofer found 2 failures!- All internal links
OK. Ran on 213 files! HTML-Proofer finished successfully. | |

|17/09/2021 |/People/CecilSinclair1.html updated | |

|14/09/2021 |IDArc/GD467_1 to IDArc/GD467_4_36 index.html.slim files
made present | |

|12/09/2021 |All What the Press said about us Internal links sorted,many
html2slim done. | |

|08/06/2021 |External Links checked with cd ~/.wine/drive_c/Program
Files/Xenu; wine Xenu.exe. Press/GN/ Converted to .erb and added up tp
GN048ScotsInterest.html.erb | |

|date | | |

|3/2020 |Found this Jeff Meek, 2015, Scottish Churches, Morality and
Homosexual Law Reform, 1957-1980,
https://www.cambridge.org/core/journals/journal-of-ecclesiastical-history/article/scottish-churches-morality-and-homosexual-law-reform-19571980/5ED4C9CBB8BB2A70D5FF5D2FFC5A00CC
The Journal of Ecclesiastical History, Vol. 66, Issue 3 , July 2015,
pp. 596-613. This article includes a reference 85 to Newsletter of the
Paisley & District SHRG, no 6, accessed 7 May 2013. NLS request 20200304
| |NLS request 20200304

|2/2020 |All links referring to The Knitting Circle at
``http://myweb.lsbu.ac.uk/~stafflag/'' or
``http://www.knittingcircle.org.uk/'' are now directed to the
WayBackMachine. The knittingcircle.org.uk found there was last spidered
according to the cache in https://archive.org/web/web.php
https://web.archive.org/web/20080511180810/http://www.knittingcircle.org.uk/ | |

|11 May 2008 |The first spider was
https://web.archive.org/web/20061202022637/http://www.knittingcircle.org.uk/ | |

|2 Dec 2006 |. ``Last altered 1st. August, 2006.'' URL waiting
assignment to another owner when spidered in 2 Jan 2009. | |

|11/2018 |Transferred to new host. HTML5 & CS3 changes started. | |

|6/2018 |Started to add links to online images of
a[href=``Press/GlasgowHerald/GlasgowHerald1976.html''] Glasgow Herald
1976 | |

|10/2017
|`Find out more about     :link:https://www.youtube.com/watch?v=GUc22xogV1Q"[Love Song To Lavender Menace]   play by James Ley at Lyceum, Edinburgh, 20171012 to 20171023. Author talks in a  :link:https://youtu.be/rjymNcgSCHY"[clip (accessed 2017-10-08)]   recorded in Waterstones, Princess St in which he states that that store was previously Scotland's first gay night club "Fire Island" (which I visited frequently in the 80s). He says that Lavender Menace started in the cloak room of the night club in 1987. Review:   :link:https://web.archive.org/web/20171016225159/https://www.thestage.co.uk/reviews/2017/love-song-lavender-menace-review-lyceum-edinburgh/[https://web.archive.org/web/20171016225159/https://www.thestage.co.uk/reviews/2017/love-song-lavender-menace-review-lyceum-edinburgh/] +
"It's 1987 and shop workers Paul and David are getting ready for a celebration of the 5th anniversary of LAVENDER MENACE, Scotland's foremost lesbian, gay, feminist bookshop. From its humble beginnings in the cloakroom of an Edinburgh nightclub, (that saw a performance from the Village People!), this trailblazing venture has become the beating heart of Edinburgh's LGBT community. But can it survive in Thatchers changing Britain of capitalism and commodification? Love Song to Lavender Menace is a funny and moving testimony to the love and passion it takes to make something happen and the loss that is felt when you have to let it go.`
| |

|9/2017 |Checking links and space on server. Problem with capitalisation
of GN/gn Gay News directory solved. Information on gay pubs being added
from Anthony Cooke, 2015, A History of Drinking: The Scottish Pub since
1700.
https://edinburghuniversitypress.com/book-a-history-of-drinking.html | |

|9/2016 |Inconsictencies in capitlisation of URLs altered. For example,
SMG in place of smg, HIV/hiv | |

|7/2016 |There have been many alterations since 2011 and now the site is
being moved to a new host and updated gradually. | |

|6/2011 |Index to GD467/1/1/1 added. | |

|2/2011 |Checking web addresses etc | |

|27/02/2008 |Note about talk on homosexuality at Polmont Young Offenders
Institution see Press/GlasgowHerald/GlasgowHerald1975.html
Glasgow Herald 1975 2 3 [Thanks Bill McConnachie] | |

|24/11/2007 |Added images of letters from Quentin Crisp & Ian Dunn,
c1976-77, :link:/IDArc/GD467_4_36/index.html[GS467/4/36] | |

|5/11/2007 |GD467/1/1/4 1970-92 Scottish Minorities Group/Scottish
Homosexual Rights Group: National constitutions
a[href=``IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/GD467_1_1_6AnnualReports.DraftsCorrespondence.html'']
GD467/1/1/6 1975-85 Scottish Minorities Group/Scottish Homosexual Rights
Group: Annual Reports: drafts and correspondence 1975-1985 |y |

|23/10/2007 |Added GD467/1/1/14 Rural Letters from National Executive
Committee members.
a[href=``IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/GD467_1_1_5.htAnnualReports1969To89.html'']
GD467/1/1/5 SMG/SHRG: Annual Reports 1969-1989 [actually to 1984] |y |

|17/10/2007 |GD467/1/1/3: Scottish Minorities Group: Early Meetings a nd
Discussion Papers Records of Outright Scotland ``Ian Dunn Archive'' 1969
in National Archives of Scotland |y |

|23/8/2007 |3rd meeting of SMG entered. Site navigation improved with
JavaScript breadcrumbing: (put in Press, except GN). |y |

|8/8/2007 |Minutes of
a[href=``IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/SMGCommitteeEarlyMinutes1969To/SMGComMeet1/index.html'']
1st ,
a[href=``IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/SMGCommitteeEarlyMinutes1969To/SMGComMeet2/index.html'']
2nd ,
a[href=``IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/SMGCommitteeEarlyMinutes1969To/SMGComMeet3/index.html'']
3rd meetings of SMG in 1969 updated. |y |

|25/7/2007
|`Start made to type "The Homosexual in Scotland" report of 3rd meeting at which name Scottish Minorities Group was adopted. See file HomosexualInScotland3rdMeeting9May1969.html. (Agenda for this photographed pic196 &7.jpg.   Ian Dunn's   a[href="IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/GD467_1_1_1IanDunnEarlyPapersAboutFoundingSMG/index.html#Summary6Mar1969"]       summary of "The Homosexual in Scotland  ", 10 March 1969 typed in full.`
| |

|22/7/2007 |Alan Horsfall added at end of file after seeing him on
Channel 4 TV tonight. | |

|15/2/2007 |Aberdeen SMG started in 1971 pages added | |

|6/2/2007 |International Gay Rights Congress 1974 - Flyer Images added |
|

|4/9/2006 |More added to GD467/1/1/1. First mention of
a[href=``IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/GD467_1_1_1IanDunnEarlyPapersAboutFoundingSMG/index.html#CloseTheatreClub'']
Close Theatre Club, Glasgow as gay venue. Copies of earliest SMG report
obtained. First mention of
a[href=``IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/GD467_1_1_1IanDunnEarlyPapersAboutFoundingSMG/index.html#MinoritiesResearchTrust'']
Minorities Research Trust: What is this? | |

|27/8/2006 |More details of members of first SMG Committee:
a[href=``IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/GD467_1_1_1IanDunnEarlyPapersAboutFoundingSMG/GD467_1_1_1_Lets_ICD_EanSimpson230169to120369.html'']
Ean Simpson, Tighnabruaich | |

|14/4/2006 |Ian Dunn’s Links with North-West Homosexual Law Reform
Committee and Esquire Clubs Limited c. 1968-9 | |

|14/4/2006 |More of GD467/1/1/1 investigated | |

|8/4/2006 |Front pages of SMG News added for years
a[href=``IDArc/GD467_6/GD467_6_1_1977.html''] 1977 end, and all
a[href=``IDArc/GD467_6/GD467_6_1_1978.html''] 1978 | |

|23/3/2006 |Article added. Domain name set up
a[href=``http://www.lgbthistoryscotland.org.uk'']
lgbthistoryscotland.org.uk | |

|20/3/2006 |Before SMG Bachelor Clan. Further details of
a[href=``IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/GD467_1_1_2.html'']
GD467/1/1/2 added | |

|20/2/2006 |HIV: The Scottish Dimension | |

|20/2/2006 |LGBT Law in Scotland: Timeline | |

|14/2/2006 |GD467/1/2/5 1983-1993 SMG/SHRG /Outright Scotland: important
legal cases Work on this in progress. | |

|7/2/2006 |GD467/2/1/7 1971-96 SMG/SHRG/Outright Scotland: publications:
examples The entire contents of this file are listed here. It contains
fine examples of early SMG leaflets. | |

|21/12/2005 |SmiG Broadsheets & Link | |

|5/12/2005 |a[href=``IDArc/GD467_6/GD467_6_1_1978.html''] 1978 SMG News
looked at a[href=``IDArc/GD467_6/GD467_6_1_1978.html#GayGranite''] Gay
Granite produced in Aberdeen 1976 SMG News:
a[href=``IDArc/GD467_6/GD467_6_1_1976.html#NEWEDITOR''] Paul Brownsey
replaces John Breslin as editor
a[href=``IDArc/GD467_6/GD467_6_1_1982.html''] Jan 1982 last edition of
Gay Scotland duplicated a[href=``IDArc/GD467_6/GD467_6_1.html''] History
of SMG News | |

|19/11/2005 |survey of Gay Club in Glasgow 1979
a[href=``/IDArc/NASNotGD467/GD248_165_HomosexualPraticeOnHMSSeahorse.html'']
Homosexual Practice On HMS Seahorse, March 1761. | |

|16/11/2005 |letter re history & description of Glasgow Gay Centre &
Club | |Link in

|10/11/2005 |Glasgow Gay Club Queens Crescent:
a[href=``GlasQueensCrescClub/QCClubAnnualReport1982.html''] Annual
Report for 1982 News paper a[href=``IDArc/GD467_5/GD467_5_5.html'']
articles on 1974 International Gay Conference
a[href=``IDArc/GD467_1/GD467_1_1IanDunnEarlySMG/SMGGeographicalScatter1_2_1970.jpg'']
Map of SMG members in 1970 | |

|2005 |Approaches made to Outright Scotland regarding making html
material available on the web | |

|early 2003 |Ian Strang started to put some of the material on the web
starting with an index of the archive. | |

|date | | |
|===

[verse]
--
   Ian look at
--
----
  comment 4 dashes start and end comment
[comment]   all of block has no output
link:href=%22IDArc/GD467_6/GD467_6_1_1971.html#SMG1971_11_9%22[ABERDEEN]

a[href=``IDArc/GD467_6/GD467_6_1_1971.html#SMG1971_11_9'']ABERDEEN

(href=``IDArc/GD467_6/GD467_6_1_1971.html#SMG1971_11_9'')[ABERDEEN]
a[href=``IDArc/GD467_6/GD467_6_1_1971.html#SMG1971_11_9''] More
expansion: Denis Wilson p a#Links[name=``Links'']  
a[href=``https://web.archive.org/web/20080511180810/http://www.knittingcircle.org.uk/''
target=“_blank”] img[src=``/images/pinkinboxsmaller.gif'' alt=“”
width=``20'' height=``21''] |.arial28 The Knitting Circle    
a[href=``https://livingmemory.org.uk/rememberWhen/'']
img[src=``/images/RememberWhenLogo.gif'' width=``197'' height=``84''
border=``0'']  

////  4 backslasses at start & end delimit comment
a[href=`https://www.ourstoryscotland.org.uk/']
img[src=``/images/OSSlogo.gif'' width=``128'' height=``64''
border=``0'']   a[href=``http://www.lgbthistory.org.uk/'']
img[src=``/images/LGBTHistoryMonthLogo.jpg'' alt=``LGBT History Month''
width=``197'' height=``74'' border=``0'']  
a[href=``http://www.codeweavers.com'' title=``CodeWeavers - CrossOver:
Windows Compatibility on Macintosh and Linux'' target=“_blank”]
img[src=``http://media.codeweavers.com/pub/crossover/marketing/link_banners/ProudCustomer_125.png''
width=``125'' height=``125'' alt=``CodeWeavers'']
(base) ian@ian-N24-25JU:~$ ^C
(base) ian@ian-N24-25JU:~$
////
----
